### ISSUE TITLE
xssme  问题

### ISSUE THREAD

**Issue by tfrnghub** [Inndy/HackmeCTF#1]
发邮件你可能没看见。
xssme 那道题，用ceye的dns是有纪录的，但是http请求，服务器没有响应。
什么情况啊？

**Comment by Inndy** [comment]
我自己測試一切正常，有可能是 IP 被封鎖，可以試試 VPS

原本的題目是不用自己的 host 就能解題的，讓 admin 給自己發訊息就行了
